name: Builds, tests & co

on:
#  pull_request:
  push:
  pull_request:
    branches: [ master ]
#  schedule:
#    # Prime the caches every Monday
#    - cron: 0 1 * * MON

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
#          - macos-latest
#          - windows-latest
        ocaml-compiler:
#         - "4.14.1"
          - "5.1"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2.1.1
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Cache _opam directory
        id: cache-opam
        uses: actions/cache@v3
        env:
          cache-name: cache-opam
        with:
          path: _opam
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('icon.opam') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('icon.opam') }}
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - run: opam install z3.4.12.5

      - run: opam install . --deps-only --with-test

      - run: opam exec -- why3 config detect

      - run: opam exec -- dune build @fmt

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

      - run: opam exec -- dune install  # required for why3 with the icon plugin

      - run: opam exec -- why3 prove -P z3 examples/boomerang.tzw
      - run: opam exec -- why3 prove -P z3 examples/boomerang_acc.tzw
      - run: opam exec -- why3 prove -P z3 examples/auction.tzw
      - run: opam exec -- why3 prove -P z3 examples/dexter2/liquidity.tzw 
